AWSTemplateFormatVersion: "2010-09-09"
Description: A CodeBuild Project to trigger AWS CLI command from AWS
Parameters:
  ProjectName:
    Type: String

Resources:

  ArtifactOutputBucket:
    Description: Bucket for build output and Maven cache
    Properties:
      BucketName: !Sub '${ProjectName}-output'
    Type: AWS::S3::Bucket
  CodeBuildServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: codebuild-service-role
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:List*
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactOutputBucket}"
                  - !Sub "arn:aws:s3:::${ArtifactOutputBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                  - logs:PutLogEvents
                  - logs:PutRetentionPolicy
                Resource: "arn:aws:logs:*"
              - Effect: Allow
                Action: cloudformation:CreateStack
                Resource: '*'
              - Effect: Allow
                Action: ecr:CreateRepository
                Resource: '*'
    Type: AWS::IAM::Role

  CodeBuildAwsCliProject:
    DependsOn: CodeBuildServiceRole
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Type: GITHUB
        Location: https://github.com/erwanjouan/aws-dev-spring-boot-dockerfile
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: eu-west-1
    Type: AWS::CodeBuild::Project