 # docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: ${JENKINS_IMAGE}
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT}:${JENKINS_PORT}
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/${HOST_USER}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock